Feature/documention update
dockstore/write_api_service pull request #12
Opened 2017-05-02 14:59 UTC by garyluu

Fixes 4 issues.

Issue #11 should be fixed as I do not see any more broken links.  Removed document line of test to change because no change should be needed.

Issue #10 write-api-service now mentions how to generate a Quay.io token.

Issue #9 Properties/configuration files were already mentioned in the respective client and service but now it's made more obvious that it's needed before running tests.

Issue #8 Badges added for develop branch

2017-05-02 16:00 UTC, denis-yuen requested changes
Needs a lot more explanation and examples

2017-05-02 16:00 UTC, denis-yuen commented on README.md
> +![Build Status](https://travis-ci.org/dockstore/write_api_service.svg?branch=develop)
This still requires more explanation. 
Imagine yourself as a developer with a passing knowledge of Dockstore that comes across this. 
Explain, what this tool is used for, who needs to use this tool, what this tool replaces, etc.

2017-05-02 16:00 UTC, denis-yuen commented on README.md
> +mvn clean install -DskipTests
The tests presumably create and tear down repos. Note which repos those are and how to configure them.

2017-05-02 16:00 UTC, denis-yuen commented on README.md
> +Running tests will require configuration/properties files for both client and service.  Do not try to run "mvn clean install" without setting up those files first.  Additionally, both client and serv
Let's have something clear and step-by-step here. I don't care whether it is in each project, but the documentation currently isn't clear at all how to get the tests running.

2017-05-02 16:00 UTC, denis-yuen commented on write-api-client/README.md
> +
Let's add some scenarios. 
Add a few example CLI invocations and explain the result.

2017-05-02 18:04 UTC, denis-yuen commented on write-api-client/README.md
>  write-api-url=http://localhost:8082/api/ga4gh/v1
Document each property, in particular, `repo` is a bit puzzling

2017-05-05 14:56 UTC, garyluu commented
Made a few documentation changes

2017-05-08 15:43 UTC, closed without merging